[build]
  publish = "workshop-site/workshop.fisioterapiathaystavares.com.br"

[[redirects]]
  from = "/obrigado"
  to = "/obrigado/"
  status = 301

[[redirects]]
  from = "/preinscricao"
  to = "/preinscricao/"
  status = 301
